site:
  baseline: Post Production Paperwork - catered to your production's needs.
  baseurl: /
  canonicalurl: true
  date:
    format: j F Y
    timezone: Europe/Paris
  description: 'Starter blog, with Netlify CMS.'
  netlify:
    cms:
      path: admin
      version: latest
    identity:
      version: v1
  pagination:
    max: 5
    path: page
  title: Jill Milne
theme: hyde
